Repository GuillermoOM/HWRM_FSFC, pull requests merged in 2024-05, with the labels that each got.

#4 added all shivan weapons
  params.txt
  source/scripts/weaponfire/gun_shivlightlasernoflash/gun_shivlightlasernoflash.wf
  source/ship/shi_nephilim/shi_nephilim.ship
  source/weapon/beam_lredcruiserturret/beam_lredcruiserturret.wepn
  source/weapon/beam_lredlucifer/beam_lredlucifer.wepn
  source/weapon/beam_lredsa/beam_lredsa.wepn
  source/weapon/beam_luciferbombardmentbeam/beam_luciferbombardmentbeam.wepn
  source/weapon/beam_sred/beam_sred.wepn
  source/weapon/beam_sredmoloch/beam_sredmoloch.wepn
  source/weapon/beam_sredturret/beam_sredturret.wepn
  source/weapon/gun_shivcollectorturret/gun_shivcollectorturret.wepn
  source/weapon/gun_shivheavylaser/gun_shivheavylaser.wepn
  source/weapon/gun_shivheavylaserturret/gun_shivheavylaserturret.wepn
  source/weapon/gun_shivlightlasers/gun_shivlightlasers.wepn
  source/weapon/gun_shivlightlaserturret/gun_shivlightlaserturret.wepn
  source/weapon/gun_shivmegalaserf/gun_shivmegalaserf.wepn
  source/weapon/gun_shivsentryturret/gun_shivsentryturret.wepn
  source/weapon/miss_shivmegabomblauncher/miss_shivmegabomblauncher.wepn
Labels: enhancement

#28 Scripts + Icons update
  source/script/races/shivan/scripts/def_build.lua
  source/ship/icons/shi_dragon.tga
  source/ship/icons/shipicons.lua
Labels: Remaster

#35 small changer
  source/ship/ter_apollo/ter_apollo.ship
Labels: fix

#81 fixes for Ares, maxim, prometheusS, trebuchet, tornado
  params.txt
  resources/HODOR/Single_Classic_To_DAE.txt
  resources/HODOR/Single_DAE_To_Remastered.txt
  source/art/fx/prometheus_beam02.lua
  source/art/fx/prometheus_combo.lua
  source/missile/miss_tornado/miss_tornado.miss
  source/missile/miss_trebuchet/miss_trebuchet.events
  source/missile/miss_trebuchet/miss_trebuchet.miss
  source/scripts/weaponfire/gun_maxim/gun_maxim.wf
  source/scripts/weaponfire/gun_prometheusS/gun_prometheusS.wf
  source/scripts/weaponfire/miss_tornado/miss_tornado.wf
  source/ship/ter_ares/ter_ares.HOD
  source/ship/ter_ares/ter_ares.events
  source/ship/ter_ares/ter_ares.ship
  source/sound/sfx/etg/weapon/largemissileblast.lua
  source/sound/sfx/etg/weapon/maxim.lua
  source/sound/sfx/etg/weapon/prometheusS.lua
  source/sound/sfx/etg/weapon/tornado.lua
  source/sound/sfx/etg/weapon/trebuchet.lua
  source/sound/sfx/ship/gtf_old.lua
  source/sound/sfx/ship/terranfighter.lua
  source/weapon/gun_maxim/gun_maxim.wepn
  source/weapon/gun_prometheusS/gun_prometheusS.wepn
  source/weapon/miss_rockeye/miss_rockeye.wepn
  source/weapon/miss_tornado/miss_tornado.wepn
  source/weapon/miss_trebuchet/miss_trebuchet.wepn
Labels: fix

#103 changed attack ability to certain ships
  source/ship/ter_apollo/ter_apollo.ship
  source/ship/ter_ares/ter_ares.ship
  source/ship/ter_hercules/ter_hercules.ship
  source/ship/ter_myrmidon/ter_myrmidon.ship
  source/ship/ter_pegasus/ter_pegasus.ship
  source/ship/ter_perseus/ter_perseus.ship
  source/ship/ter_ulysses/ter_ulysses.ship
  source/ship/ter_valkyrie/ter_valkyrie.ship
Labels: fix

#108 adjusted weapons and ships for better dogfighting, adjusted fighter template
  params.txt
  resources/script_templates/fighter.ship
  source/ship/shi_dragon/shi_dragon.ship
  source/ship/shi_manticore/shi_manticore.ship
  source/ship/ter_apollo/ter_apollo.ship
  source/ship/ter_ares/ter_ares.ship
  source/ship/ter_hercules/ter_hercules.ship
  source/ship/ter_loki/ter_loki.ship
  source/ship/ter_myrmidon/ter_myrmidon.ship
  source/ship/ter_pegasus/ter_pegasus.ship
  source/ship/ter_perseus/ter_perseus.ship
  source/ship/ter_ulysses/ter_ulysses.ship
  source/ship/ter_valkyrie/ter_valkyrie.ship
  source/weapon/gun_avenger/gun_avenger.wepn
  source/weapon/gun_banshee/gun_banshee.wepn
  source/weapon/gun_circe/gun_circe.wepn
  source/weapon/gun_disruptor/gun_disruptor.wepn
  source/weapon/gun_kayser/gun_kayser.wepn
  source/weapon/gun_lamprey/gun_lamprey.wepn
  source/weapon/gun_maxim/gun_maxim.wepn
  source/weapon/gun_ml16/gun_ml16.wepn
  source/weapon/gun_morningstar/gun_morningstar.wepn
  source/weapon/gun_prometheusR/gun_prometheusR.wepn
  source/weapon/gun_prometheusS/gun_prometheusS.wepn
  source/weapon/gun_prometheusfs1/gun_prometheusfs1.wepn
  source/weapon/gun_shivheavylaser/gun_shivheavylaser.wepn
  source/weapon/gun_shivlightlaser/gun_shivlightlaser.wepn
  source/weapon/gun_shivlightlasers/gun_shivlightlasers.wepn
  source/weapon/gun_shivmegalaser/gun_shivmegalaser.wepn
  source/weapon/gun_shivmegalaserf/gun_shivmegalaserf.wepn
  source/weapon/gun_subach/gun_subach.wepn
  source/weapon/miss_empadv/miss_empadv.wepn
  source/weapon/miss_fury/miss_fury.wepn
  source/weapon/miss_tempest/miss_tempest.wepn
Labels: fix

#109 changed attack ability on fighters
  resources/script_templates/fighter.ship
  source/ship/shi_dragon/shi_dragon.ship
  source/ship/shi_scorpion/shi_scorpion.ship
  source/ship/ter_apollo/ter_apollo.ship
  source/ship/ter_ares/ter_ares.ship
  source/ship/ter_hercules/ter_hercules.ship
  source/ship/ter_myrmidon/ter_myrmidon.ship
  source/ship/ter_pegasus/ter_pegasus.ship
  source/ship/ter_perseus/ter_perseus.ship
  source/ship/ter_ulysses/ter_ulysses.ship
  source/ship/ter_valkyrie/ter_valkyrie.ship
Labels: fix

#113 added disrupter sound from fs1
  params.txt
  source/scripts/weaponfire/gun_disruptorfs1/gun_disruptorfs1.wf
  source/ship/ter_athena/ter_athena.ship
  source/sound/sfx/etg/weapon/disruptorfs1.fda
  source/sound/sfx/etg/weapon/disruptorfs1.lua
  source/weapon/gun_disruptorfs1/gun_disruptorfs1.wepn
Labels: fix

#116 Modified pihrana so it works as it should
  params.txt
  source/missile/miss_cluster_baby/miss_cluster_baby.miss
  source/missile/miss_pihrana/miss_pihrana.miss
  source/weapon/miss_pihrana/miss_pihrana.wepn
  source/weapon/miss_pihranaturret/miss_pihranaturret.wepn
Labels: fix

#123 added debris meshes and engine glow to fenris
  resources/HODOR/Mass_DAE_to_Remastered.txt
  resources/script_templates/cruiser.ship
  source/art/fx/debris_meshes/aeolus1.HOD
  source/art/fx/debris_meshes/aeolus2.HOD
  source/art/fx/debris_meshes/aeolus3.HOD
  source/art/fx/debris_meshes/aeolus4.HOD
  source/art/fx/debris_meshes/cain1.HOD
  source/art/fx/debris_meshes/cain2.HOD
  source/art/fx/debris_meshes/cain3.HOD
  source/art/fx/debris_meshes/colossus1.HOD
  source/art/fx/debris_meshes/colossus10.HOD
  source/art/fx/debris_meshes/colossus2.HOD
  source/art/fx/debris_meshes/colossus3.HOD
  source/art/fx/debris_meshes/colossus4.HOD
  source/art/fx/debris_meshes/colossus5.HOD
  source/art/fx/debris_meshes/colossus6.HOD
  source/art/fx/debris_meshes/colossus7.HOD
  source/art/fx/debris_meshes/colossus8.HOD
  source/art/fx/debris_meshes/colossus9.HOD
  source/art/fx/debris_meshes/demon1.HOD
  source/art/fx/debris_meshes/demon2.HOD
  source/art/fx/debris_meshes/demon3.HOD
  source/art/fx/debris_meshes/demon4.HOD
  source/art/fx/debris_meshes/demon5.HOD
  source/art/fx/debris_meshes/demon6.HOD
  source/art/fx/debris_meshes/demon7.HOD
  source/art/fx/debris_meshes/hades1.HOD
  source/art/fx/debris_meshes/hades2.HOD
  source/art/fx/debris_meshes/hades3.HOD
  source/art/fx/debris_meshes/hades4.HOD
  source/art/fx/debris_meshes/hades5.HOD
  source/art/fx/debris_meshes/hades6.HOD
  source/art/fx/debris_meshes/hades7.HOD
  source/art/fx/debris_meshes/hecate1.HOD
  source/art/fx/debris_meshes/hecate2.HOD
  source/art/fx/debris_meshes/hecate3.HOD
  source/art/fx/debris_meshes/hecate4.HOD
  source/art/fx/debris_meshes/hecate5.HOD
  source/art/fx/debris_meshes/hecate6.HOD
  source/art/fx/debris_meshes/hecate7.HOD
  source/art/fx/debris_meshes/hecate8.HOD
  source/ship/ter_fenris/ter_fenris.hod
  source/ship/ter_fenris/ter_fenris.ship
Labels: Remaster

#124 reenabled missiles on erinyes and fixed tornado
  params.txt
  source/ship/ter_erinyes/ter_erinyes.ship
  source/weapon/miss_tornado/miss_tornado.wepn
Labels: fix

#125 small fixes on terran laser turret weapon
  params.txt
  resources/script_templates/cruiser.ship
  source/art/fx/blob_turrets/terpulse_anibitmap.anim
  source/art/fx/prometheus_combo.lua
  source/art/fx/ter_pulse.lua
  source/scripts/weaponfire/gun_terlaser/gun_terlaser.wf
  source/ship/ter_charybdis/ter_charybdis.ship
  source/ship/ter_colossus/ter_colossus.ship
  source/ship/ter_deimos/ter_deimos.ship
  source/ship/ter_fenris/ter_fenris.ship
  source/ship/ter_hades/ter_hades.ship
  source/ship/ter_hecate/ter_hecate.ship
  source/ship/ter_leviathan/ter_leviathan.ship
  source/ship/ter_orion/ter_orion.ship
  source/ship/ter_zephyrus/ter_zephyrus.ship
  source/sound/sfx/etg/weapon/terlaser.fda
  source/sound/sfx/etg/weapon/terlaser.lua
  source/weapon/gun_terhugeturret2/gun_terhugeturret2.wepn
  source/weapon/gun_terhugeturret3/gun_terhugeturret3.wepn
  source/weapon/gun_terlaser_gimble/gun_terlaser_gimble.wepn
  source/weapon/gun_terlaser_turret/gun_terlaser_turret.wepn
Labels: fix

#128 fix aeolus and missiles
  params.txt
  source/missile/miss_harbinger/miss_harbinger.miss
  source/missile/miss_helios/miss_helios.miss
  source/ship/ter_aeolus/ter_aeolus.hod
  source/ship/ter_aeolus/ter_aeolus.ship
  source/ship/ter_fenris/ter_fenris.ship
  source/weapon/beam_sgreen/beam_sgreen.wepn
  source/weapon/gun_flak_gimble/gun_flak_gimble.wepn
  source/weapon/gun_flak_turret/gun_flak_turret.wepn
Labels: fix

#139 fixes on nameplate code and ai code
  params.txt
  source/ai/default/classdef.lua
  source/ai/default/cpubuild.lua
  source/scripts/custom_scripts/add_nameplate.lua
  source/scripts/races/shivan/props/default.lua
  source/scripts/races/shivan/scripts/ai_build.lua
  source/scripts/races/terran/props/default.lua
  source/scripts/races/terran/scripts/ai_build.lua
  source/scripts/races/terran/scripts/crate_locate.lua
  source/ship/ter_orion/ter_orion.ship
Labels: fix

#140 added observer faction
  source/scripts/races/observer.lua
  source/scripts/races/observer/props/default.lua
  source/scripts/rules/fs_deathmatch.lua
Labels: enhancement
